# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_auto_20161021_1614'),
        ('restaurant_app', '0006_auto_20161021_1516'),
    ]

    operations = [
    ]
