# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_merge_20161021_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='appetizer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='item',
            name='entree',
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.CharField(choices=[('a', 'appetizer'), ('e', 'entree'), ('b', 'beverage'), ('d', 'dessert'), ('s', 'side')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
