# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_auto_20161022_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='paid',
            field=models.BooleanField(),
        ),
    ]
